/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/I06njjO54jZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Input } from "@/components/ui/input"
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"

export function mainScreens() {
  return (
    <div className="flex min-h-screen bg-gray-100">
      <aside className="w-64 bg-white border-r">
        <div className="flex items-center justify-between p-4 border-b">
          <h1 className="text-xl font-bold">Logo</h1>
          <Button variant="ghost" size="icon">
            <XIcon className="w-6 h-6" />
          </Button>
        </div>
        <nav className="p-4 space-y-2">
          <Link href="#" className="flex items-center p-2 text-blue-500 bg-blue-100 rounded-md" prefetch={false}>
            <HomeIcon className="w-6 h-6" />
            <span className="ml-2">Home</span>
          </Link>
          <Link href="#" className="flex items-center p-2 rounded-md" prefetch={false}>
            <CompassIcon className="w-6 h-6" />
            <span className="ml-2">Explore</span>
          </Link>
          <Link href="#" className="flex items-center p-2 rounded-md" prefetch={false}>
            <BellIcon className="w-6 h-6" />
            <span className="ml-2">Notifications</span>
          </Link>
          <Link href="#" className="flex items-center p-2 rounded-md" prefetch={false}>
            <MailIcon className="w-6 h-6" />
            <span className="ml-2">Messages</span>
          </Link>
          <Link href="#" className="flex items-center p-2 rounded-md" prefetch={false}>
            <StarIcon className="w-6 h-6" />
            <span className="ml-2">Premium</span>
          </Link>
          <Link href="#" className="flex items-center p-2 rounded-md" prefetch={false}>
            <ListIcon className="w-6 h-6" />
            <span className="ml-2">Lists</span>
          </Link>
          <Link href="#" className="flex items-center p-2 rounded-md" prefetch={false}>
            <BookmarkIcon className="w-6 h-6" />
            <span className="ml-2">Bookmarks</span>
          </Link>
          <Link href="#" className="flex items-center p-2 rounded-md" prefetch={false}>
            <UsersIcon className="w-6 h-6" />
            <span className="ml-2">Communities</span>
          </Link>
          <Link href="#" className="flex items-center p-2 rounded-md" prefetch={false}>
            <ShieldIcon className="w-6 h-6" />
            <span className="ml-2">Verified Orgs</span>
          </Link>
          <Link href="#" className="flex items-center p-2 rounded-md" prefetch={false}>
            <UserIcon className="w-6 h-6" />
            <span className="ml-2">Profile</span>
          </Link>
          <Link href="#" className="flex items-center p-2 rounded-md" prefetch={false}>
            <MoveHorizontalIcon className="w-6 h-6" />
            <span className="ml-2">More</span>
          </Link>
        </nav>
        <div className="p-4">
          <Button className="w-full">Post</Button>
        </div>
        <div className="flex items-center p-4 border-t">
          <Avatar>
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>II</AvatarFallback>
          </Avatar>
          <div className="ml-2">
            <p className="font-semibold">Ivo Ivanov</p>
            <p className="text-sm text-muted-foreground">@IvoUIflip</p>
          </div>
        </div>
      </aside>
      <main className="flex-1 p-4">
        <div className="flex items-center justify-between pb-4 border-b">
          <Tabs defaultValue="for-you">
            <TabsList>
              <TabsTrigger value="for-you">For you</TabsTrigger>
              <TabsTrigger value="following">Following</TabsTrigger>
              <TabsTrigger value="saas-growth">SaaS Growth</TabsTrigger>
              <TabsTrigger value="all-startups">All Startups</TabsTrigger>
              <TabsTrigger value="fintech-startups">Fintech Startups</TabsTrigger>
              <TabsTrigger value="web-3">Web 3</TabsTrigger>
              <TabsTrigger value="product-design">Product Design</TabsTrigger>
            </TabsList>
          </Tabs>
          <Input type="search" placeholder="Search" className="w-64" />
        </div>
        <div className="pt-4 space-y-4">
          <Card>
            <CardHeader className="flex items-center space-x-2">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>U</AvatarFallback>
              </Avatar>
              <Input placeholder="What is happening?!" className="flex-1" />
              <Button>Post</Button>
            </CardHeader>
            <CardContent className="flex items-center justify-between pt-2 space-x-4">
              <ImageIcon className="w-6 h-6 text-muted-foreground" />
              <VideoIcon className="w-6 h-6 text-muted-foreground" />
              <VoteIcon className="w-6 h-6 text-muted-foreground" />
              <SmileIcon className="w-6 h-6 text-muted-foreground" />
              <CalendarIcon className="w-6 h-6 text-muted-foreground" />
              <LocateIcon className="w-6 h-6 text-muted-foreground" />
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex items-center space-x-2">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>II</AvatarFallback>
              </Avatar>
              <div>
                <p className="font-semibold">Ivo Ivanov</p>
                <p className="text-sm text-muted-foreground">@IvoUIflip · Just now</p>
              </div>
            </CardHeader>
            <CardContent className="pt-2">
              <p>Some of the projects I've been working on recently in 10 seconds ✌️</p>
              <img src="/placeholder.svg" alt="Project" className="w-full mt-2 rounded-md" />
            </CardContent>
            <CardFooter className="flex items-center justify-between pt-2">
              <div className="flex items-center space-x-2">
                <MessageCircleIcon className="w-5 h-5 text-muted-foreground" />
                <span>23</span>
              </div>
              <div className="flex items-center space-x-2">
                <RepeatIcon className="w-5 h-5 text-muted-foreground" />
                <span>1</span>
              </div>
              <div className="flex items-center space-x-2">
                <HeartIcon className="w-5 h-5 text-muted-foreground" />
                <span>143</span>
              </div>
              <div className="flex items-center space-x-2">
                <ShareIcon className="w-5 h-5 text-muted-foreground" />
                <span>2.34K</span>
              </div>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader className="flex items-center space-x-2">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>AD</AvatarFallback>
              </Avatar>
              <div>
                <p className="font-semibold">Adham Dannaway</p>
                <p className="text-sm text-muted-foreground">@AdhamDannaway · 12 mins</p>
              </div>
            </CardHeader>
            <CardContent className="pt-2">
              <p>Created this example landing page to test out the @practicalUI design system.</p>
              <p>Works well so far and it really speeds up the design process.</p>
              <p>Nearly there 🙌 Join the waitlist to be notified when the design system is released</p>
              <img src="/placeholder.svg" alt="Design System" className="w-full mt-2 rounded-md" />
            </CardContent>
          </Card>
        </div>
      </main>
      <aside className="w-80 p-4 space-y-4">
        <div className="p-4 bg-white rounded-md shadow-md">
          <h2 className="text-lg font-semibold">Who to follow</h2>
          <div className="flex items-center justify-between pt-4">
            <div className="flex items-center space-x-2">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JC</AvatarFallback>
              </Avatar>
              <div>
                <p className="font-semibold">Jane Cooper</p>
                <p className="text-sm text-muted-foreground">@JCooper</p>
              </div>
            </div>
            <Button variant="outline" size="sm">
              Follow
            </Button>
          </div>
          <div className="flex items-center justify-between pt-4">
            <div className="flex items-center space-x-2">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>CF</AvatarFallback>
              </Avatar>
              <div>
                <p className="font-semibold">Cody Fisher</p>
                <p className="text-sm text-muted-foreground">@codyfisher</p>
              </div>
            </div>
            <Button variant="outline" size="sm">
              Follow
            </Button>
          </div>
          <div className="flex items-center justify-between pt-4">
            <div className="flex items-center space-x-2">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>GH</AvatarFallback>
              </Avatar>
              <div>
                <p className="font-semibold">Guy Hawkins</p>
                <p className="text-sm text-muted-foreground">@GuyHawkins</p>
              </div>
            </div>
            <Button variant="outline" size="sm">
              Follow
            </Button>
          </div>
          <Link href="#" className="block pt-4 text-sm font-semibold text-blue-500" prefetch={false}>
            Show more
          </Link>
        </div>
        <div className="p-4 bg-white rounded-md shadow-md">
          <h2 className="text-lg font-semibold">Bulgaria trends</h2>
          <ul className="pt-4 space-y-2">
            <li className="flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold">1. Sports · Trending</p>
                <p className="text-sm text-muted-foreground">Grigor Dimitrov</p>
              </div>
              <p className="text-sm">45.2K posts</p>
            </li>
            <li className="flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold">2. Politics · Trending</p>
                <p className="text-sm text-muted-foreground">Ukraine</p>
              </div>
              <p className="text-sm">235K posts</p>
            </li>
            <li className="flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold">3. Trending</p>
                <p className="text-sm text-muted-foreground">Bulgaria</p>
              </div>
              <p className="text-sm">68K posts</p>
            </li>
            <li className="flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold">4. Politics</p>
                <p className="text-sm text-muted-foreground">Elections</p>
              </div>
              <p className="text-sm">45.2K posts</p>
            </li>
            <li className="flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold">5. Sports · Trending</p>
                <p className="text-sm text-muted-foreground">Kobrat Pulev</p>
              </div>
              <p className="text-sm">37K posts</p>
            </li>
            <li className="flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold">6. Technology</p>
                <p className="text-sm text-muted-foreground">ChatGPT</p>
              </div>
              <p className="text-sm">45.2K posts</p>
            </li>
            <li className="flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold">7. Technology · Trending</p>
                <p className="text-sm text-muted-foreground">#DesignSubscription</p>
              </div>
              <p className="text-sm">45.2K posts</p>
            </li>
          </ul>
        </div>
      </aside>
    </div>
  )
}

function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function BookmarkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function CompassIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function HeartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function ImageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  )
}


function ListIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  )
}


function LocateIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MessageCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  )
}


function MoveHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="18 8 22 12 18 16" />
      <polyline points="6 8 2 12 6 16" />
      <line x1="2" x2="22" y1="12" y2="12" />
    </svg>
  )
}


function RepeatIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m17 2 4 4-4 4" />
      <path d="M3 11v-1a4 4 0 0 1 4-4h14" />
      <path d="m7 22-4-4 4-4" />
      <path d="M21 13v1a4 4 0 0 1-4 4H3" />
    </svg>
  )
}


function ShareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>
  )
}


function ShieldIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
    </svg>
  )
}


function SmileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function VideoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
      <rect x="2" y="6" width="14" height="12" rx="2" />
    </svg>
  )
}


function VoteIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 12 2 2 4-4" />
      <path d="M5 7c0-1.1.9-2 2-2h10a2 2 0 0 1 2 2v12H5V7Z" />
      <path d="M22 19H2" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
